language: bash

services:
  - docker

script: bash .travis-build.sh || || travis_terminate 1

deploy:
  provider: script
  script: bash .travis-deploy.sh || travis_terminate 1
  on:
    tags: true
    branch: master
