language: bash

services:
  - docker

script:
  # Node Pipeline
  - docker pull superdispatch/node-pipeline || true
  - docker build --pull --cache-from superdispatch/node-pipeline --tag superdispatch/node-pipeline node-pipeline
  - docker run --rm -v $(pwd)/node-pipeline/test.sh:/test.sh superdispatch/node-pipeline bash test.sh

deploy:
  provider: script
  script: bash .travis-deploy.sh
  on:
    tags: true
    branch: master
  env:
    secure: ADSQlDGXyQpMbCFwkSKN5yvwmBc9VmhLySOK65AUUrlZfazqRRBD1HonRnPBGKHEmUnkvulVQQjrtX/9e4SOdRon0ANUr383402bs4oVldTcfee+9m+08q1sFa4lUOf07hCbBcW4pP7zM+AKzncHqxXSkEvPjijT9ytYjUf/KhJ9CVKMjI0AHY7qhSssEB8NC0DWZ0YrTKoR74YXxNbnFmbLtNSUXninR946x1qPHdCBALnDM192FV8irswze+ht5ciqzq1iUvWIWYj+Rc7J9ttPD1cJY8cu8Zdi3mJJn/9QZ0F+M1Q7rYjOW4MXCvnsA1ZCIAoR5pjjdBrymGXN7PUQL31vV7wJTbO0GTgFndbhRsAUPW58NDqL4v3BEYy1qstwhNC7MAXsG7DHStaP+oAm4B9UIg0wed82+WwuWtIBIGfDb7m/zaBKpPlGfnl2BJgdsP+6Q5fREfPFi0ISsKCwnDfUB10+fCiC8cwt5gNyXmiK4aqqrWeGxarWh819Cp+NHonolVyiZzg7R1q/N9PyBgSr0QtMLA8Rn6OUdSps508uGmowanfACTSbP9jFht1nPurPjNd5mOeQmFWQZWRJtqvHC1bespyPza47n2NkK6ynjvZZuH6jsUDhpge9UNmxYpqKuCx9b+s+yPUbS/dw3Zay/i8bvJn2Oh0/EQ4=
