language: bash

services:
  - docker

script:
  # Node Pipeline
  - docker pull superdispatch/node-pipeline || true
  - docker build --pull --cache-from superdispatch/node-pipeline --tag superdispatch/node-pipeline node-pipeline
  - docker run --rm -v $(pwd)/node-pipeline/test.sh:/test.sh superdispatch/node-pipeline bash test.sh

deploy:
  provider: script
  script: bash .travis-deploy.sh
  on:
    tags: true
    branch: master
  env:
    secure: M5rk3Kpxl6mgTTJkgKotgYJMXUDRNFWacoPvQzO9fTKTgZpg5RLWprqf8I8VMTyf0OtYdxGv/hXWVHndt2DwGQxoPYsENg6TRrAQ+B1BeHQOKBPv0JrVESAntK/dkE6jXgz3bCgMUwRGvnjuXvsNIEakNxgshQu5IhfxHfPzytd/pshySbSS1rplXen7YmzNrIKnhUUAVTBJ0cce3qa6aG+MbXpeO/0xpJyBxvGcRYue2lZxwoxosnIam3FHRaYhUA+w1wTM/cSQFyLMw+TA0T8k2VCKHN9Azb8b0tWf0RgrO8J7FbE6UxoLk03ofqjNuPV3SxbvF3f8KjJUAQ3tcPdIwoFu8X1mO0IJPyByn1EkfdkVmjAGZzcwKWq+ziHeZWDskNF7Zlnl0oyg66YKbaq45MTk1vhO6GDjUCBqNrl7QFGe2K/JnrijDyMQ03+HF6pzHldFYEWQmMTrjtR10OZY5qbM8GmqhVffMl+5Wl/DXDaHS667yFIO8G24HkOyt6nkhwVuLdUMF893N7n1TUmtXmW3741/6Rfc9x1P5YUWMT/6vtKHWnGcDD+VBbWnVHBncRX9K/RJQki/7rD2qK5bzw80P7j4nIUul8kGppgH63i4BVGZgzuICLenNwAzXFN+w/C6pOS7ek0LqoB9rc7JmZAePIUDrNuhkNcL6D8=
