version: 2.1

jobs:
  main:
    machine: true
    parameters:
      image:
        type: string
      tag:
        type: string
        default: ''
    steps:
      - checkout
      - run:
          name: Pull
          command: docker pull superdispatch/<< parameters.image >>:latest || true
      - run:
          name: Build
          command: docker build --pull --cache-from superdispatch/<< parameters.image >>:latest --tag superdispatch/<< parameters.image >> << parameters.image >>
      - when:
          condition: << parameters.tag >>
          steps:
            - run:
                name: Deploy
                command: |
                  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                  docker tag superdispatch/<< parameters.image >> superdispatch/<< parameters.image >>:<< parameters.tag >>
                  docker tag superdispatch/<< parameters.image >> superdispatch/<< parameters.image >>:latest
                  docker push superdispatch/<< parameters.image >>:<< parameters.tag >>
                  docker push superdispatch/<< parameters.image >>:latest
                  curl -X POST https://hooks.microbadger.com/images/superdispatch/node-pipeline/${MICROBADGER_NODE_ID} > /dev/null

workflows:
  version: 2
  ci:
    jobs:
      - main:
          name: build-node-pipeline
          image: node-pipeline
          filters:
            tags:
              ignore: /.*/

      - main:
          context: docker
          name: deploy-node-pipeline
          image: node-pipeline
          tag: ${CIRCLE_TAG//-node-pipeline/}
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+.[0-9]+.[0-9]+-node-pipeline$/

